#[derive(Debug, Clone)]
pub enum Key {
    Space,
    ExclamationMark,
    QutationMark,
    NumberSign,
    DollarSign,
    PercentSign,
    Ampersand,
    Apostrophe,
    LeftParenthesis,
    RightParenthesis,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    N0,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,
    Colon,
    Semicolon,
    LessThan,
    Equals,
    GreaterThan,
    Questinmark,
    AT,
    BracketLeft,
    Backslash,
    BracketRight,
    Circumflex,
    Underscore,
    Grave,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    BraceLeft,
    Bar,
    BraceRight,
    Tilde,
    NoBreakSpace,
    InvertedExclamationMark,
    CentSign,
    PoundSign,
    CurrencySign,
    YenSign,
    BrokenBar,
    SectionSign,
    Diaresis,
    CopyrightSign,
    Female,
    Guillemontleft,
    NotSign,
    Hyphen,
    Registered,
    Macron,
    Degree,
    PlusMinus,
    TwoSuperior,
    ThreeSuperior,
    Acute,
    Mu,
    Paragraph,
    Periodcentered,
    Cedilla,
    OneSuperior,
    Masculine,
    GuillemontRight,
    OneQuarter,
    OneHalf,
    ThreeQuarters,
    QuestionDown,
    Agrave,
    Aacute,
    Acircumflex,
    Atilde,
    Adiaresis,
    Aring,
    AE,
    Ccedilla,
    Egrave,
    Eacute,
    Ecircumflex,
    Ediaresis,
    Igrave,
    Iacute,
    Icircumflex,
    Idiaresis,
    Eth,
    Ntilde,
    Ograve,
    Oacute,
    Ocircumflex,
    Otilde,
    Odiaresis,
    Multiply,
    Oslash,
    Ugrave,
    Uacute,
    Ucircumflex,
    Udiaresis,
    Yacute,
    Thorn,
    Ssharp,
    Division,
    Ydiaresis,
    MonitorBrightnessUp,
    MonitorBrightnessDown,
    KeyboardLightToggle,
    KeyboardBrightnesUp,
    KeyboardBrightnesDown,
    MonitorBrightnessCycle,
    Standby,
    AudioLowerVolume,
    AudioMute,
    AudioRaiseVolume,
    AudioPlay,
    AudioStop,
    AudioPrev,
    AudioNext,
    AudioRecord,
    HomePage,
    Mail,
    Start,
    Search,
    Backspace,
    Tab,
    Linefeed,
    Clear,
    Return,
    Pause,
    ScrollLock,
    SysReq,
    Escape,
    Delete,
    Home,
    Left,
    Up,
    Right,
    Down,
    PageUp,
    PageDown,
    End,
    Begin,
    Select,
    Print,
    Execute,
    Insert,
    Undo,
    Redo,
    Menu,
    Find,
    Cancel,
    Help,
    Break,
    ModeSwitch,
    NumLock,
    KeypadSpace,
    KeypadTab,
    KeypadEnter,
    KeypadF1,
    KeypadF2,
    KeypadF3,
    KeypadF4,
    KeypadHome,
    KeypadLeft,
    KeypadUp,
    KeypadRight,
    KeypadDown,
    KeypadPageUp,
    KeypadPageDown,
    KeypadEnd,
    KeypadBegin,
    KeypadInsert,
    KeypadDelete,
    KeypadEqual,
    KeypadMultiply,
    KeypadAdd,
    KeypadSeparator,
    KeypadSubtract,
    KeypadDecimal,
    KeypadDivide,
    Keypad0,
    Keypad1,
    Keypad2,
    Keypad3,
    Keypad4,
    Keypad5,
    Keypad6,
    Keypad7,
    Keypad8,
    Keypad9,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    ShiftLeft,
    ShiftRight,
    ControlLeft,
    ControlRight,
    CapsLock,
    ShiftLock,
    MetaLeft,
    MetaRight,
    AltLeft,
    AltRight,
    SuperLeft,
    SuperRight,
    HyperLeft,
    HyperRight,
    Fn,
    MicMute,
    Settings,
    NotSupported(u64),
}

impl Key {
    pub fn from_keysym(sym: u64) -> Self {
        match sym {
            0x20 => Self::Space,
            0x21 => Self::ExclamationMark,
            0x22 => Self::QutationMark,
            0x23 => Self::NumberSign,
            0x24 => Self::DollarSign,
            0x25 => Self::PercentSign,
            0x26 => Self::Ampersand,
            0x27 => Self::Apostrophe,
            0x28 => Self::LeftParenthesis,
            0x29 => Self::RightParenthesis,
            0x2A => Self::Asterisk,
            0x2B => Self::Plus,
            0x2C => Self::Comma,
            0x2D => Self::Minus,
            0x2E => Self::Period,
            0x2F => Self::Slash,
            0x30 => Self::N0,
            0x31 => Self::N1,
            0x32 => Self::N2,
            0x33 => Self::N3,
            0x34 => Self::N4,
            0x35 => Self::N5,
            0x36 => Self::N6,
            0x37 => Self::N7,
            0x38 => Self::N8,
            0x39 => Self::N9,
            0x3a => Self::Colon,
            0x3b => Self::Semicolon,
            0x3c => Self::LessThan,
            0x3d => Self::Equals,
            0x3e => Self::GreaterThan,
            0x3f => Self::Questinmark,
            0x40 => Self::AT,
            0x41 => Self::A,
            0x42 => Self::B,
            0x43 => Self::C,
            0x44 => Self::D,
            0x45 => Self::E,
            0x46 => Self::F,
            0x47 => Self::G,
            0x48 => Self::H,
            0x49 => Self::I,
            0x4A => Self::J,
            0x4B => Self::K,
            0x4C => Self::L,
            0x4D => Self::M,
            0x4E => Self::N,
            0x4F => Self::O,
            0x50 => Self::P,
            0x51 => Self::Q,
            0x52 => Self::R,
            0x53 => Self::S,
            0x54 => Self::T,
            0x55 => Self::U,
            0x56 => Self::V,
            0x57 => Self::W,
            0x58 => Self::X,
            0x59 => Self::Y,
            0x5A => Self::Z,
            0x5B => Self::BracketLeft,
            0x5C => Self::Backslash,
            0x5D => Self::BracketRight,
            0x5E => Self::Circumflex,
            0x5F => Self::Underscore,
            0x60 => Self::Grave,
            0x61 => Self::A,
            0x62 => Self::B,
            0x63 => Self::C,
            0x64 => Self::D,
            0x65 => Self::E,
            0x66 => Self::F,
            0x67 => Self::G,
            0x68 => Self::H,
            0x69 => Self::I,
            0x6A => Self::J,
            0x6B => Self::K,
            0x6C => Self::L,
            0x6D => Self::M,
            0x6E => Self::N,
            0x6F => Self::O,
            0x70 => Self::P,
            0x71 => Self::Q,
            0x72 => Self::R,
            0x73 => Self::S,
            0x74 => Self::T,
            0x75 => Self::U,
            0x76 => Self::V,
            0x77 => Self::W,
            0x78 => Self::X,
            0x79 => Self::Y,
            0x7A => Self::Z,
            0x7B => Self::BraceLeft,
            0x7C => Self::Bar,
            0x7D => Self::BraceRight,
            0x7E => Self::Tilde,
            // space
            0xA0 => Self::NoBreakSpace,
            0xA1 => Self::InvertedExclamationMark,
            0xA2 => Self::CentSign,
            0xA3 => Self::PoundSign,
            0xA4 => Self::CurrencySign,
            0xA5 => Self::YenSign,
            0xA6 => Self::BrokenBar,
            0xA7 => Self::SectionSign,
            0xA8 => Self::Diaresis,
            0xA9 => Self::CopyrightSign,
            0xAA => Self::Female,
            0xAB => Self::Guillemontleft,
            0xAC => Self::NotSign,
            0xAD => Self::Hyphen,
            0xAE => Self::Registered,
            0xAF => Self::Macron,
            0xB0 => Self::Degree,
            0xB1 => Self::PlusMinus,
            0xB2 => Self::TwoSuperior,
            0xB3 => Self::ThreeSuperior,
            0xB4 => Self::Acute,
            0xB5 => Self::Mu,
            0xB6 => Self::Paragraph,
            0xB7 => Self::Periodcentered,
            0xB8 => Self::Cedilla,
            0xB9 => Self::OneSuperior,
            0xBA => Self::Masculine,
            0xBB => Self::GuillemontRight,
            0xBC => Self::OneQuarter,
            0xBD => Self::OneHalf,
            0xBE => Self::ThreeQuarters,
            0xBF => Self::QuestionDown,
            0xC0 => Self::Agrave,
            0xC1 => Self::Aacute,
            0xC2 => Self::Acircumflex,
            0xC3 => Self::Atilde,
            0xC4 => Self::Adiaresis,
            0xC5 => Self::Aring,
            0xC6 => Self::AE,
            0xC7 => Self::Ccedilla,
            0xC8 => Self::Egrave,
            0xC9 => Self::Eacute,
            0xCA => Self::Ecircumflex,
            0xCB => Self::Ediaresis,
            0xCC => Self::Igrave,
            0xCD => Self::Iacute,
            0xCE => Self::Icircumflex,
            0xCF => Self::Idiaresis,
            0xD0 => Self::Eth,
            0xD1 => Self::Ntilde,
            0xD2 => Self::Ograve,
            0xD3 => Self::Oacute,
            0xD4 => Self::Ocircumflex,
            0xD5 => Self::Otilde,
            0xD6 => Self::Odiaresis,
            0xD7 => Self::Multiply,
            0xD8 => Self::Oslash,
            0xD9 => Self::Ugrave,
            0xDA => Self::Uacute,
            0xDB => Self::Ucircumflex,
            0xDC => Self::Udiaresis,
            0xDD => Self::Yacute,
            0xDE => Self::Thorn,
            0xDF => Self::Ssharp,
            0xE0 => Self::Agrave,
            0xE1 => Self::Aacute,
            0xE2 => Self::Acircumflex,
            0xE3 => Self::Atilde,
            0xE4 => Self::Adiaresis,
            0xE5 => Self::Aring,
            0xE6 => Self::AE,
            0xE7 => Self::Ccedilla,
            0xE8 => Self::Egrave,
            0xE9 => Self::Eacute,
            0xEA => Self::Ecircumflex,
            0xEB => Self::Ediaresis,
            0xEC => Self::Igrave,
            0xED => Self::Iacute,
            0xEE => Self::Icircumflex,
            0xEF => Self::Idiaresis,
            0xF0 => Self::Eth,
            0xF1 => Self::Ntilde,
            0xF2 => Self::Ograve,
            0xF3 => Self::Oacute,
            0xF4 => Self::Ocircumflex,
            0xF5 => Self::Otilde,
            0xF6 => Self::Odiaresis,
            0xF7 => Self::Division,
            0xF8 => Self::Oslash,
            0xF9 => Self::Ugrave,
            0xFA => Self::Uacute,
            0xFB => Self::Ucircumflex,
            0xFC => Self::Udiaresis,
            0xFD => Self::Yacute,
            0xFE => Self::Thorn,
            0xFF => Self::Ydiaresis,
            // space
            0xFF08 => Self::Backspace,
            0xFF09 => Self::Tab,
            0xFF0A => Self::Linefeed,
            0xFF0B => Self::Clear,
            0xFF0D => Self::Return,
            0xFF13 => Self::Pause,
            0xFF14 => Self::ScrollLock,
            0xFF15 => Self::SysReq,
            0xFF1B => Self::Escape,
            0xFFFF => Self::Delete,
            0xFF50 => Self::Home,
            0xFF51 => Self::Left,
            0xFF52 => Self::Up,
            0xFF53 => Self::Right,
            0xFF54 => Self::Down,
            0xFF55 => Self::PageUp,
            0xFF56 => Self::PageDown,
            0xFF57 => Self::End,
            0xFF58 => Self::Begin,
            0xFF60 => Self::Select,
            0xFF61 => Self::Print,
            0xFF62 => Self::Execute,
            0xFF63 => Self::Insert,
            0xFF65 => Self::Undo,
            0xFF66 => Self::Redo,
            0xFF67 => Self::Menu,
            0xFF68 => Self::Find,
            0xFF69 => Self::Cancel,
            0xFF6A => Self::Help,
            0xFF6B => Self::Break,
            0xFF6E => Self::ModeSwitch,
            0xFF6F => Self::NumLock,
            0xFF80 => Self::KeypadSpace,
            0xFF89 => Self::KeypadTab,
            0xFF8D => Self::KeypadEnter,
            0xFF91 => Self::KeypadF1,
            0xFF92 => Self::KeypadF2,
            0xFF93 => Self::KeypadF3,
            0xFF94 => Self::KeypadF4,
            0xFF95 => Self::KeypadHome,
            0xFF96 => Self::KeypadLeft,
            0xFF97 => Self::KeypadUp,
            0xFF98 => Self::KeypadRight,
            0xFF99 => Self::KeypadDown,
            0xFF9A => Self::KeypadPageUp,
            0xFF9B => Self::KeypadPageDown,
            0xFF9C => Self::KeypadEnd,
            0xFF9D => Self::KeypadBegin,
            0xFF9E => Self::KeypadInsert,
            0xFF9F => Self::KeypadDelete,
            0xFFBD => Self::KeypadEqual,
            0xFFAA => Self::KeypadMultiply,
            0xFFAB => Self::KeypadAdd,
            0xFFAC => Self::KeypadSeparator,
            0xFFAD => Self::KeypadSubtract,
            0xFFAE => Self::KeypadDecimal,
            0xFFAF => Self::KeypadDivide,
            0xFFB0 => Self::Keypad0,
            0xFFB1 => Self::Keypad1,
            0xFFB2 => Self::Keypad2,
            0xFFB3 => Self::Keypad3,
            0xFFB4 => Self::Keypad4,
            0xFFB5 => Self::Keypad5,
            0xFFB6 => Self::Keypad6,
            0xFFB7 => Self::Keypad7,
            0xFFB8 => Self::Keypad8,
            0xFFB9 => Self::Keypad9,
            0xFFBE => Self::F1,
            0xFFBF => Self::F2,
            0xFFC0 => Self::F3,
            0xFFC1 => Self::F4,
            0xFFC2 => Self::F5,
            0xFFC3 => Self::F6,
            0xFFC4 => Self::F7,
            0xFFC5 => Self::F8,
            0xFFC6 => Self::F9,
            0xFFC7 => Self::F10,
            0xFFC8 => Self::F11,
            0xFFC9 => Self::F12,
            0xFFE1 => Self::ShiftLeft,
            0xFFE2 => Self::ShiftRight,
            0xFFE3 => Self::ControlLeft,
            0xFFE4 => Self::ControlRight,
            0xFFE5 => Self::CapsLock,
            0xFFE6 => Self::ShiftLock,
            0xFFE7 => Self::MetaLeft,
            0xFFE8 => Self::MetaRight,
            0xFFE9 => Self::AltLeft,
            0xFFEA => Self::AltRight,
            0xFFEB => Self::SuperLeft,
            0xFFEC => Self::SuperRight,
            0xFFED => Self::HyperLeft,
            0xFFEE => Self::HyperRight,
            // space
            0x1008FF02 => Self::MonitorBrightnessUp,
            0x1008FF03 => Self::MonitorBrightnessDown,
            0x1008FF04 => Self::KeyboardLightToggle,
            0x1008FF05 => Self::KeyboardBrightnesUp,
            0x1008FF06 => Self::KeyboardBrightnesDown,
            0x1008FF07 => Self::MonitorBrightnessCycle,
            0x1008FF10 => Self::Standby,
            0x1008FF11 => Self::AudioLowerVolume,
            0x1008FF12 => Self::AudioMute,
            0x1008FF13 => Self::AudioRaiseVolume,
            0x1008FF14 => Self::AudioPlay,
            0x1008FF15 => Self::AudioStop,
            0x1008FF16 => Self::AudioPrev,
            0x1008FF17 => Self::AudioNext,
            0x1008FF18 => Self::HomePage,
            0x1008FF19 => Self::Mail,
            0x1008FF1A => Self::Start,
            0x1008FF1B => Self::Search,
            0x1008FF1C => Self::AudioRecord,
            0x1008FF2B => Self::Fn,
            0x1008FFB2 => Self::MicMute,
            0x1008FF81 => Self::Settings,
            x => Self::NotSupported(x),
        }
    }
}
